connectionsSqlWhereClause: |
  WHERE sv_id IN (SERVICE IDS)

maxAccessWalkingTravelTimeFromOriginToFirstStopMinutes: 20
maxAccessWalkingTravelTimeFromLastStopToDestinationMinutes: 20
maxTransferWalkingTravelTimeMinutes: 5
minWaitingTimeMinutes: 5
tryNextModeIfRoutingFails: false
noResultNextAccessTimeMinutesIncrement: 10
maxNoResultNextAccessTimeMinutes: 60

