name: C/C++ CI

on:
  push:
    branches: [ v2c ]
  pull_request:
    branches: [ v2c ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install deps
      run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev libexpat1-dev libjsoncpp-dev libncurses5-dev libcapnp-dev capnproto
    - name: Gen configure
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
