name: C/C++ CI

on:
  push:
    branches: [ v2c ]
  pull_request:
    branches: [ v2c ]

jobs:
  build:
    name: Test build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
       os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install deps
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev libexpat1-dev libjsoncpp-dev libncurses5-dev libcapnp-dev capnproto
    - name: Install deps
      if: matrix.os == 'macOS-latest'
      run: |
          brew update
          brew install boost
          brew install capnp          
    - name: Gen configure
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check

